name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.13
  ynotes_components:
    path: ../
  flutter_phoenix: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Asap
      fonts:
        - asset: fonts/Asap-Regular.ttf
          weight: 400
        - asset: fonts/Asap-Medium.ttf
          weight: 500
        - asset: fonts/Asap-SemiBold.ttf
          weight: 600
        - asset: fonts/Asap-Bold.ttf
          weight: 700
