name: ynotes_packages
description: yNotes' components library.
publish_to: 'none'
version: 0.4.3
homepage: https://github.com/EduWireApps/ynotes-packages

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  flutter_responsive_breakpoints: ^0.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
